### ISSUE TITLE
Cannot run system commands with MSYS2 on Windows

### ISSUE THREAD

**Issue by mhkline** [pimalaya/himalaya#254]
Maybe I'm just doing something dumb here, but I can't seem to get `pass show` to work correctly under MSYS2 on Windows.

I have a configuration for checking my personal outlook email, and I confirmed it works with `echo password` as the `passwd cmd`. But I simply can't get it to work with `pass show`.

Here's a dump of some debug info:

```
[2021-11-02T18:44:33Z DEBUG himalaya::config::account_entity] init account `live`
[2021-11-02T18:44:33Z TRACE himalaya::config::account_entity] Account {
        name: "live",
        from: "Redacted",
        downloads_dir: "/c/Users/redacted/Downloads",
        sig: Some(
            "-- \n--\nBest,\nRedacted",
        ),
        default_page_size: 10,
        watch_cmds: [],
        default: false,
        email: "redacted@live.com",
        imap_host: "outlook.office365.com",
        imap_port: 993,
        imap_starttls: false,
        imap_insecure: false,
        imap_login: "redacted@live.com",
        imap_passwd_cmd: "pass show outlook-live | tr -d '\\n'",
        smtp_host: "smtp.office365.com",
        smtp_port: 587,
        smtp_starttls: true,
        smtp_insecure: false,
        smtp_login: "redacted@live.com",
        smtp_passwd_cmd: "pass show outlook-live | tr -d '\n'",
    }
[2021-11-02T18:44:33Z DEBUG himalaya::domain::smtp::smtp_service] init SMTP service
[2021-11-02T18:44:33Z DEBUG himalaya::domain::msg::msg_arg] default list command matched
[2021-11-02T18:44:33Z TRACE himalaya::domain::msg::msg_handler] page size: 10
[2021-11-02T18:44:33Z DEBUG himalaya::domain::imap::imap_service] create TLS builder
[2021-11-02T18:44:33Z DEBUG himalaya::domain::imap::imap_service] insecure: false
[2021-11-02T18:44:33Z DEBUG himalaya::domain::imap::imap_service] create client
[2021-11-02T18:44:33Z DEBUG himalaya::domain::imap::imap_service] host: outlook.office365.com
[2021-11-02T18:44:33Z DEBUG himalaya::domain::imap::imap_service] port: 993
[2021-11-02T18:44:33Z DEBUG himalaya::domain::imap::imap_service] starttls: false
[2021-11-02T18:44:33Z DEBUG himalaya::domain::imap::imap_service] create session
[2021-11-02T18:44:33Z DEBUG himalaya::domain::imap::imap_service] login: redacted@live.com
[2021-11-02T18:44:33Z DEBUG himalaya::domain::imap::imap_service] passwd cmd: pass show outlook-live | tr -d '\n'
Error: cannot login to IMAP server

Caused by:
    No Response: LOGIN failed.
```

You can see here that I'm even trying to strip newlines out of the return value of `pass show`, but it doesn't make a difference.

My GPG key does require a passphrase. I figured out how to make it prompt for this on the command line instead of a GUI dialog. Also, the gpg-agent is running, so it only prompts once (and I would think `himalaya` wouldn't make it prompt again).

Thus, I suspect that `himalaya` isn't able to find the `pass` binary due to some MSYS2isms. But I'm not sure how to debug further.

Any ideas?

By the way, this a really neat utility. Looking forward to using it!

**Comment by soywod** [comment]
I think it is the maximum you can get from the logger. The command passed in the config is just executed as it is:

https://github.com/soywod/himalaya/blob/f9775ae8afff236c7f948d4d2e0014146dcaed0e/src/output/output_utils.rs#L7

I never tested this part of the code on a Windows machine, maybe something is missing. Did you try to give the full path of `pass`? When you start himalaya (if you did not start anything before that requires the gpg-agent), does it prompt your GPG passphrase?

**Comment by mhkline** [comment]
> Did you try to give the full path of pass? 

Yes. I tried this using the mingw style path, .i.e., `/c/msys64/usr/bin/pass`. No difference.

> When you start himalaya (if you did not start anything before that requires the gpg-agent), does it prompt your GPG passphrase?

I hadn't tried this. Good suggestion. It does NOT prompt for the passphrase.

```
redacted@redacted MINGW64 /c/Users/redacted/Code
$ gpgconf.exe --kill gpg-agent

redacted@redacted MINGW64 /c/Users/redacted/Code
$ gpg-connect-agent.exe /bye
gpg-connect-agent: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established

...

[2021-11-02T19:23:57Z DEBUG himalaya::domain::imap::imap_service] passwd cmd: pass show outlook-live | tr -d '\n'
Error: cannot login to IMAP server

Caused by:
    No Response: LOGIN failed.
```

```rust
Command::new("cmd").args(&["/C", cmd]).output() 
```
I think this is likely the issue. In the `MSYS2` shell, the command should just be run without modification.

In fact, I tried running `pass` from a "normal" Windows shell, and it won't even run. If I add `.exe` to `pass`, it complains it isn't compatible with the machine. Clearly it is since it runs in the MSYS shell though.

I'm already building from source, so I guess I could try to modify this and see if it works.

Thanks!

**Comment by soywod** [comment]
> Seems to work if I use the linux-style command instead of the Windows one.

So it looks like the condition for the target_os is not necessary. Is the `MSYS2` a standard in Windows env? I would like to know if other Windows users will be impacted by this removed condition.

**Comment by mhkline** [comment]
It definitely won't work like that for all windows users.

MSYS2 I guess is fairly popular for people like me, who want a posix-like environment under windows. Git bash is another popular shell for this purpose, and I would think would want the same change.

Is it possible to detect if the user is in a bash shell on windows?

**Comment by soywod** [comment]
It is a good question, I need to dig!

**Comment by mhkline** [comment]
Yeah I'm honestly not very familiar with how these foreign shells work on windows.

For example, both Git Bash and MSYS2 use MinGW64. What exactly MinGW provides vs MSYS2 or Git Bash is kind of a mystery to me. But maybe MinGW is the thing to detect?

**Comment by soywod** [comment]
Is `sh` available on `MSYS2`? If so, could you try to run the command `sh -c "pass"`?

**Comment by mhkline** [comment]
Yes, this works. This was the change I made to make it work on my system, but I wasn't sure how to detect the environment to make the change conditional.

```diff
diff --git a/src/output/output_utils.rs b/src/output/output_utils.rs
index 4f44494..bdf0b08 100644
--- a/src/output/output_utils.rs
+++ b/src/output/output_utils.rs
@@ -4,7 +4,8 @@ use std::process::Command;
 /// TODO: move this in a more approriate place.
 pub fn run_cmd(cmd: &str) -> Result<String> {
     let output = if cfg!(target_os = "windows") {
-        Command::new("cmd").args(&["/C", cmd]).output()
+        //Command::new("cmd").args(&["/C", cmd]).output()
+        Command::new("sh").arg("-c").arg(cmd).output()
     } else {
         Command::new("sh").arg("-c").arg(cmd).output()
     }?;
```

**Comment by soywod** [comment]
Maybe the [`target_env`](https://doc.rust-lang.org/reference/conditional-compilation.html#target_env) is what we are looking for? Could you try to add (no matter where, maybe in the `main.rs`) `println!("target_env: {:?}", std::env::var("CARGO_CFG_TARGET_ENV"));` and see the output?

**Comment by soywod** [comment]
I think that checking the `$MSYSTEM` is the way to go. See https://stackoverflow.com/questions/37460073/msys-vs-mingw-internal-environment-variables. I will propose a fix for the next release, I let you know!

**Comment by soywod** [comment]
I added a condition on the `$MSYSTEM` env var in the last release [`v0.6.1`](https://github.com/soywod/himalaya/releases/tag/v0.6.1), could you try again?

**Comment by soywod** [comment]
Feel free to reopen if the issue persists!

**Comment by mhkline** [comment]
Ok, sorry I haven't had a chance to check it. I've moved over to using Powershell at this point because it felt like I had a lot of issues with MSYS2 as a daily driver. Thanks so much for looking at this!
