### ISSUE TITLE
Separate the CLI from the lib module

### ISSUE THREAD

**Issue by soywod** [pimalaya/himalaya#340]
The lib should be split into its own module, and the CLI should be considered as a regular frontend.

**Comment by TornaxO7** [comment]
I'll try to find some time in the evening after doing my work now so I can approach this issue. Meanwhile, could you please summarize a little bit what still has to be done?

**Comment by soywod** [comment]
I think you can leave it, I'm already on it and it's a total mess x) I will do it by chunks because it's too heavy. But what could really helpful at the moment is to check / fix new bugs (many issue were opened recently), and I lake of time to treat all of them. I'm thinking about https://github.com/soywod/himalaya/issues/370, https://github.com/soywod/himalaya/issues/373, https://github.com/soywod/himalaya/issues/359, https://github.com/soywod/himalaya/issues/292 etc.

**Comment by soywod** [comment]
Or if you want sth more challenging and interesting you have https://github.com/soywod/himalaya/issues/341, it can be developed aside independently.

**Comment by soywod** [comment]
@TornaxO7 I think I finally moved everything to the lib folder, what a damn hard and messy work! I just need to clean up and we can move forward.

**Comment by TornaxO7** [comment]
That's nice to hear! I'm still stuck adding `chumsky` to the parser at the moment... I'm sorry that it takes so long

**Comment by soywod** [comment]
No problem dude, don't worry. Be ready, good news are coming soon :tada:

**Comment by soywod** [comment]
Released in the [v0.6.0](https://github.com/soywod/himalaya/releases/tag/v0.6.0) :tada:

**Comment by dvdsk** [comment]
Thats great! thanks a lot this must have taken quite a lot of effort!

**Comment by soywod** [comment]
Hell yes, a good thing done! I will focus a while on fixing bugs to make this new base as solid as possible, then I will be able to take care of big features like the offline #342, email composer #341 or contact completion #49.
