### ISSUE TITLE
How to disable encryption?

### ISSUE THREAD

**Issue by wucke13** [pimalaya/himalaya#347]
I want to use plain IMAP/SMTP, without encryption. How can I enable this? I always get

```console
Error: cannot connect to IMAP server

Caused by:
    error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
```

despite already having 

```toml
imap-starttls = false
```

in my config.

**Comment by soywod** [comment]
`imap-starttls` is for using the STARTTLS protocol instead of SSL/TLS. To disable encryption you can use `imap-insecure`.

**Comment by wucke13** [comment]
I do have `imap-insecure = true` in my config, so this does __not__ work @soywod

**Comment by soywod** [comment]
Mmmh strange. Could you share your config (himalaya config, system, os etc)?

**Comment by palb91** [comment]
Hello,

I meet the same problem. I use MS Office at work, so I set up a `davmail` gateway on my machine. Everything being in local on my machine, I did not set up any certificate.
`mbsync` works great with this setup (with `SSLType None`), I tried to run some IMAP commands directly from `telnet`, it works well too.

However, `himalaya` doesn't work. I have the same error message than the first post of this issue and no other error in the debug logs:

```console
$ RUST_LOG=debug himalaya
[2022-03-28T14:26:52Z INFO  himalaya::compl::compl_args] entering completion command matcher
[2022-03-28T14:26:52Z INFO  himalaya::config::deserialized_config] begin: try to parse config from path
[2022-03-28T14:26:52Z DEBUG himalaya::config::deserialized_config] path: None
[2022-03-28T14:26:52Z INFO  himalaya::config::deserialized_config] end: try to parse config from path
[2022-03-28T14:26:52Z INFO  himalaya::config::account_config] begin: parsing account and backend configs from config and account name
[2022-03-28T14:26:52Z DEBUG himalaya::config::account_config] account name: "default"
[2022-03-28T14:26:52Z INFO  himalaya::config::account_config] end: parsing account and backend configs from config and account name
[2022-03-28T14:26:52Z INFO  himalaya::backends::imap::imap_args] entering imap command matcher
[2022-03-28T14:26:52Z INFO  himalaya::config::account_args] >> account command matcher
[2022-03-28T14:26:52Z INFO  himalaya::config::account_args] << account command matcher
[2022-03-28T14:26:52Z INFO  himalaya::mbox::mbox_args] entering mailbox command matcher
[2022-03-28T14:26:52Z INFO  himalaya::msg::msg_args] entering message command matcher
[2022-03-28T14:26:52Z INFO  himalaya::msg::msg_args] default list command matched
[2022-03-28T14:26:52Z DEBUG himalaya::msg::msg_handlers] page size: 50
[2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] create TLS builder
[2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] insecure: false
[2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] create client
[2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] host: localhost
[2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] port: 1143
[2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] starttls: false
Error: cannot connect to IMAP server

Caused by:
    error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
```

I set up `imap-insecure = true` in my configuration, however, according to the wiki, `imap-insecure` allows invalid certificates, does it work with no certificate?

Finally, I have the same problem for sending mails:

```console
$ himalaya write
(s)end, (e)dit, (l)ocal/(r)emote draft or (d)iscard? s
Error: Connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:

Caused by:
    0: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
    1: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
    2: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
```

(`RUST_LOG=debug` doesn't show anything interesting).

---

* **OS:** Arch Linux (5.16.16-arch1-1)
* **davmail:** 6.0.1
* **himalaya:** 0.5.10 (from community/himalaya)
* **himalaya configuration:**

```ini
name = "Pierre-Albéric TROUPLIN"
downloads-dir = "/home/pat/tmp"

[work]
default = true
email = "me@work.com"

smtp-host = "localhost"
#smtp-host = "127.0.0.1"
smtp-port = 1025
smtp-login = "me@work.com"
smtp-passwd-cmd = "bw get password mail.work.com"
smtp-insecure = true

imap-host = "localhost"
#imap-host = "127.0.0.1"
imap-port = 1143
imap-login = "me@work.com"
imap-passwd-cmd = "bw get password mail.work.com"
imap-insecure = false
```

**Comment by gpncarl** [comment]
+1

**Comment by soywod** [comment]
It looks like message never arrived, sorry for the delay. Indeed we miss a config option to disable SSL. For now, even the insecure option still uses the SSL module. I will try to add it ASAP.

**Comment by soywod** [comment]
I think you right. Even if insecure is on, the TLS layer is still used,
which leads to openssl runtime errors. I could introduce a new option
`imap-ssl` at true by default, and if `imap-ssl` and `imap-starttls`
are `false` then encryption is disabled. What do you think?

On 28 Mar 2022, at 16:53 (+0200), soywod/himalaya wrote:
> Hello,
> 
> I meet the same problem. I use MS Office at work, so I set up a `davmail` gateway on my machine. Everything being in local on my machine, I did not set up any certificate.
> `mbsync` works great with this setup (with `SSLType None`), I tried to run some IMAP commands directly from `telnet`, it works well too.
> 
> However, `himalaya` doesn't work. I have the same error message than the first post of this issue and no other error in the debug logs:
> 
> ```console
> $ RUST_LOG=debug himalaya
> [2022-03-28T14:26:52Z INFO  himalaya::compl::compl_args] entering completion command matcher
> [2022-03-28T14:26:52Z INFO  himalaya::config::deserialized_config] begin: try to parse config from path
> [2022-03-28T14:26:52Z DEBUG himalaya::config::deserialized_config] path: None
> [2022-03-28T14:26:52Z INFO  himalaya::config::deserialized_config] end: try to parse config from path
> [2022-03-28T14:26:52Z INFO  himalaya::config::account_config] begin: parsing account and backend configs from config and account name
> [2022-03-28T14:26:52Z DEBUG himalaya::config::account_config] account name: "default"
> [2022-03-28T14:26:52Z INFO  himalaya::config::account_config] end: parsing account and backend configs from config and account name
> [2022-03-28T14:26:52Z INFO  himalaya::backends::imap::imap_args] entering imap command matcher
> [2022-03-28T14:26:52Z INFO  himalaya::config::account_args] >> account command matcher
> [2022-03-28T14:26:52Z INFO  himalaya::config::account_args] << account command matcher
> [2022-03-28T14:26:52Z INFO  himalaya::mbox::mbox_args] entering mailbox command matcher
> [2022-03-28T14:26:52Z INFO  himalaya::msg::msg_args] entering message command matcher
> [2022-03-28T14:26:52Z INFO  himalaya::msg::msg_args] default list command matched
> [2022-03-28T14:26:52Z DEBUG himalaya::msg::msg_handlers] page size: 50
> [2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] create TLS builder
> [2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] insecure: false
> [2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] create client
> [2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] host: localhost
> [2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] port: 1143
> [2022-03-28T14:26:52Z DEBUG himalaya::backends::imap::imap_backend] starttls: false
> Error: cannot connect to IMAP server
> 
> Caused by:
>  error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
> ```
> 
> I set up `imap-insecure = true` in my configuration, however, according to the wiki, `imap-insecure` allows invalid certificates, does it work with no certificate?
> 
> Finally, I have the same problem for sending mails:
> 
> ```console
> $ himalaya write
> (s)end, (e)dit, (l)ocal/(r)emote draft or (d)iscard? s
> Error: Connection error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
> 
> Caused by:
>  0: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
>  1: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
>  2: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
> ```
> 
> (`RUST_LOG=debug` doesn't show anything interesting).
> 
> ---
> 
> * **OS:** Arch Linux (5.16.16-arch1-1)
> * **davmail:** 6.0.1
> * **himalaya:** 0.5.10 (from community/himalaya)
> * **himalaya configuration:**
> 
> ```ini
> name = "Pierre-Albéric TROUPLIN"
> downloads-dir = "/home/pat/tmp"
> 
> [work]
> default = true
> email = ***@***.***"
> 
> smtp-host = "localhost"
> #smtp-host = "127.0.0.1"
> smtp-port = 1025
> smtp-login = ***@***.***"
> smtp-passwd-cmd = "bw get password mail.work.com"
> smtp-insecure = true
> 
> imap-host = "localhost"
> #imap-host = "127.0.0.1"
> imap-port = 1143
> imap-login = ***@***.***"
> imap-passwd-cmd = "bw get password mail.work.com"
> imap-insecure = false
> ```
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/soywod/himalaya/issues/347#issuecomment-1080756012
> You are receiving this because you modified the open/close state.
> 
> Message ID: ***@***.***>

-- 
Cordialement
Clément DOUIN
Développeur Web Full-Stack
https://soywod.me

**Comment by soywod** [comment]
Added the option `imap-ssl` and `smtp-ssl` in the last release [`v0.6.1`](https://github.com/soywod/himalaya/releases/tag/v0.6.1) :tada:
