### ISSUE TITLE
 version `GLIBC_2.29' not found (required by himalaya)

### ISSUE THREAD

**Issue by CompuRoot** [pimalaya/himalaya#356]
Still officially supported Debian versions 9, 10 won't run recent `himalaya` due to dependency on  GLIBC_2.29.

Is it possible to compile `himalaya` against `musl` to make it truly portable or at least lower requirement to avoid be dependent on most recent GLIBC ?

**Comment by soywod** [comment]
It is a very good question, I need to dig. Any help is welcomed!

**Comment by MCOfficer** [comment]
Tested it, one needs to jump a few hoops but it's doable:

- Install musl and musl-gcc (on debian-ish, that's `musl` and `musl-tools`)
- Install the musl target: `rustup target install x86_64-unknown-linux-musl`
- Set these to make OpenSSL compile:
	```
	export PKG_CONFIG_ALLOW_CROSS=1
	export OPENSSL_STATIC=true
	```
	(this is where a `rustls` feature could be helpful)

- Build it: `cargo build --release --target x86_64-unknown-linux-musl`

**Comment by soywod** [comment]
I tried but it does not compile :disappointed: `DSO missing from command line`

**Comment by CompuRoot** [comment]
The only way I know to make truly portable across platform a program on amd64/linux is to spin out in virtual machine (or docker) with  AlpineLinux (that natively using musl instead of glib ) and compile it there

**Comment by MCOfficer** [comment]
Yeah, that's probably easier. You don't even need a linux, here's me on Windows 10:

```sh
❯ docker run -v "${PWD}:/volume" --rm -t clux/muslrust:stable cargo build --release
 # magic is happening
❯ ubuntu2004.exe run ldd target/x86_64-unknown-linux-musl/release/himalaya 
        statically linked
❯ ubuntu2004.exe run ./target/x86_64-unknown-linux-musl/release/himalaya -V
himalaya 0.6.1
```

See https://github.com/clux/muslrust

**Comment by soywod** [comment]
So technically I can add a musl build to the release via GitHub Actions? I will give a shot and let you know!

**Comment by CompuRoot** [comment]
> So technically I can add a musl build to the release via GitHub Actions? I will give a shot and let you know!

**Thank you!** 
Unfortunately `rust` isn't my language where I can contribute :(

**Comment by soywod** [comment]
@CompuRoot could you try the artifact `himalaya-musl` generated by the CI? https://github.com/soywod/himalaya/actions/runs/3712824669

**Comment by soywod** [comment]
Awesome, I will add the config to the deployment script. The build will be added to the release section!

**Comment by CompuRoot** [comment]
Thank you so much !!!

**Comment by CompuRoot** [comment]
> @CompuRoot could you try the artifact `himalaya-musl` generated by the CI? https://github.com/soywod/himalaya/actions/runs/3712824669

It works !!!        
I deeply appreciate what you did !!!
