### ISSUE TITLE
Decode mailbox names from modified UTF7

### ISSUE THREAD

**Issue by pleshevskiy** [pimalaya/himalaya#370]
IMAP mailbox names fully support Unicode but use a rather exotic ASCII-safe modified UTF7 encoding.
See https://tools.ietf.org/html/rfc3501#section-5.1.3

```
➜  ~ himalaya mailboxes

DELIM │NAME                               │ATTRIBUTES
|     │&BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1- │\HasNoChildren, Unmarked, \Sent
|     │&BBgEQQRFBD4ENARPBEkEOAQ1-         │\HasNoChildren, Unmarked
|     │&BCEEPwQwBDw-                      │\HasNoChildren, Unmarked, \Junk
|     │&BCMENAQwBDsENQQ9BD0ESwQ1-         │\HasNoChildren, Marked, \Trash
|     │&BCcENQRABD0EPgQyBDgEOgQ4-         │\HasNoChildren, Unmarked, \Drafts
|     │Archive                            │\HasNoChildren, Unmarked
|     │INBOX                              │\HasNoChildren, Unmarked, \NoInferiors
|     │Notes                              │\HasNoChildren, Unmarked
```

it would be really cool if himalaya could decode them

**Comment by soywod** [comment]
Ouch, I was not even aware of it. Thanks for pointing it out!

**Comment by pleshevskiy** [comment]
I found these crates that can decode base64 utf7, but no one encode them.
1. https://crates.io/crates/charset
2. https://crates.io/crates/utf7-imap

I don't know. Should we encode it to choose a mailbox or not...

**Comment by newca12** [comment]
FYI [utf7-imap](https://crates.io/crates/utf7-imap) can now also encode IMAP-UTF7.

**Comment by soywod** [comment]
Added in the last release [`v0.6.1`](https://github.com/soywod/himalaya/releases/tag/v0.6.1) :tada:
