### ISSUE TITLE
Support Unix pipes in password commands

### ISSUE THREAD

**Issue by pleshevskiy** [pimalaya/himalaya#373]
I use passwordstore (pass) to display a password for imap and I have a password for email with metadata. 

Himalaya cannot find my password in the first line

## Steps to reproduce:
1. pass add example
2. add content
    ```
    secret
    url: http://example.com
    login: my@example.com
    ```
3. configure pass_cmd for himalaya `pass show example`

## Expected behavior
himalaya successfully logged in

## Actual behavior
```
Error: cannot login to IMAP server

Caused by:
    No Response: LOGIN failed.
```

**Comment by soywod** [comment]
Himalaya is not aware of tools used to retrieve passwords. And it is a good think. What you propose goes against this principle. I would suggest instead to use your own tools to extract the first line. For eg.: `pass show example | head -n 1`.

**Comment by pleshevskiy** [comment]
@soywod actually himalaya doesn't support `pipe` in password command

**Comment by soywod** [comment]
It's true that the pipe is not managed properly by the password command, but it should work. Have you tried? Anyway, I reopen this issue for supporting well the pipe. It is already done for SMTP commands, so it should not be so difficult to do.

**Comment by soywod** [comment]
Added since the `v0.6.1`.
