### ISSUE TITLE
Find a way to preview HTML message

### ISSUE THREAD

**Issue by soywod** [pimalaya/himalaya#471]
When you need to open an email in your browser for example, the flow is not so smooth. You need first to message read --html --no-headers > email.html then chromium email.html. If images are in attachments you cannot see them. This issue stands for finding a smoother alternative.

A first idea could be to split the read command into 2:

- read (for everything related to reading text content)
- export (for everything related to exporting/moving messages). The --raw flag disappear and would be the default behaviour of the export command.

**Comment by soywod** [comment]
Feature landed on [`v1.0.0`](https://github.com/pimalaya/himalaya/tree/v1.0.0) branch, see the changelog for more details (once merged on `master`).

**Comment by parisni** [comment]
Hi, great feature. Did not found any reference/documentation, including the changelog note mentionned though.

**Comment by soywod** [comment]
Nice catch, I either did a mistake during the merge or just totally forgot the entry in the CHANGELOG. I will update it. Regarding the feature, see `himalaya message read --help` and `himalaya message export --help`.

**Comment by parisni** [comment]
> Regarding the feature, see himalaya message read --help and himalaya message export --help.

Yeah, i eventually found it by myself in the cli help, which is the first place for documentation anyway. 

Works really fine BTW, using browser to display html is definitelly unix compliant
