### ISSUE TITLE
Basic run after install fails because of 'envelope' not found

### ISSUE THREAD

**Issue by piotryordanov** [pimalaya/himalaya#481]
I did a brand new install using both cargo and pacman.

In both cases, `himalaya` runs fine, but I get the following problem:

```sh
❯ himalaya envelope list 
error: unrecognized subcommand 'envelope'

  tip: some similar subcommands exist: 'n', 'help'

Usage: himalaya [OPTIONS] [COMMAND]

For more information, try '--help'.
```

FYI, this same command is used in the `himalaya-vim` plugins, which then fails to run.
Any idea what i might have missed?

**Comment by soywod** [comment]
You may run an outdated version of the CLI. I would advise to use the `master` branch till the next release. See the `Installation > Cargo`:

```
$ cargo install --git https://github.com/pimalaya/himalaya.git himalaya
```

**Comment by soywod** [comment]
Just a precision: the CLI was on a `v1.0.0-beta` for a while. Since it's officially a beta, repositories were not updated and all remained on the latest `v0.9.0`.

**Comment by piotryordanov** [comment]
I confirm that this worked for me.
FYI, both the `himlaya-git` and `himlaya` packages on arch aren't providing the latest :(

Thx for the swift response

**Comment by soywod** [comment]
> FYI, both the `himlaya-git` and `himlaya` packages on arch aren't providing the latest :(

Yep, I am aware of that. Looks like `v0.X` is seen as more stable than `v1.X-beta`, which was not the case. The `v1` is on its way and should fix all these problems!
