### ISSUE TITLE
Is it possible to configure Key Bindings?

### ISSUE THREAD

**Issue by thjbdvlt** [pimalaya/himalaya#485]
hello :-)

i am very new to himalaya and i already love it but i am using a non-qwerty/azerty/... keyboard layout, and i want to use `u`/`e` instead of `j`/`k` for selection (i do not have arrows, and `k` is far away from my home row).

is it possible? or do i have to change the source files and compile it by myself (i do not know Rust)?

(i haven't seen anything like key bindings in the sample config file.)

thank you for reading (and for the free software)

**Comment by soywod** [comment]
Hello,

> i want to use `u`/`e` instead of `j`/`k` for selection (i do not have arrows, and `k` is far away from my home row).

Which selection are you referring to?

**Comment by thjbdvlt** [comment]
Hello!
I mean the interactive selection after (for example) i have written a message:

```
What would you like to do with this message?
  Send it
> Edit it again
  Save it as local draft
  Save it as remote draft
  Discard it
```

But since you asked, i feel like i misunderstood something and this interface is not specific to Himalaya (it looks like the `gh` cli tool)! So i just need to find what it is. Sorry for my message, then! I close the discussion

**Comment by soywod** [comment]
No it is part of Himalaya, it comes from the [`inquire`](https://github.com/mikaelmello/inquire) Rust lib that Himalaya relies on. But keybinds do not seem to be customizable.

**Comment by soywod** [comment]
Ah, looks like an issue is already opened for that specific purpose: https://github.com/mikaelmello/inquire/issues/70

**Comment by thjbdvlt** [comment]
I'm sorry i haven't seen this opened Issue! I will check its developpement. Thank you very much :-)
