### ISSUE TITLE
account wizard does not set Default on empty config

### ISSUE THREAD

**Issue by TimSeyschab** [pimalaya/himalaya#489]
Right now the account wizard is not setting a default config when creating a fresh configuration.

The configure method in https://github.com/pimalaya/himalaya/blob/master/src/account/wizard.rs#L15 is just creating a Default TomlAccountConfig:

```golang
let mut config = TomlAccountConfig {
        email: email.to_string(),
        ..Default::default()
};
``` 

This does not set `default: Some(true),`, probably because the wizard can or should be called from a configured instance later on.

**Comment by soywod** [comment]
This has been fixed recently but not yet applied for Himalaya CLI: https://github.com/pimalaya/tui/blob/6e51e2565afec4b44bdaaaacc0eacbe63bba4fe0/src/himalaya/wizard.rs#L43

The fix should land very soon. I will close the issue when it's ready!

**Comment by soywod** [comment]
The fix landed on `pimalaya-tui-refactor`, which should be merged into `master` very soon.
