### ISSUE TITLE
Contacts completion

### ISSUE THREAD

**Issue by soywod** [pimalaya/himalaya#49]

**Comment by soywod** [comment]
External tool in progress: https://github.com/soywod/cardamom

**Comment by jasonccox** [comment]
I was playing around with this yesterday and implemented basic contact completion (assuming users have a command to search their contacts) in the Vim plugin: #250 Let me know what you think!

**Comment by soywod** [comment]
Moved here: https://todo.sr.ht/~soywod/himalaya/24.
