### ISSUE TITLE
Folders with Maildir backend

### ISSUE THREAD

**Issue by renesat** [pimalaya/himalaya#490]
I'm trying to use himalaya with my existing Maildir (mbsync). But this only works with specific folders in Maildir (like inbox), but when I set root as the mail folder nothing shows up.

This when `maildir.root-dir = "~/.mail/mainmail`:
```
> himalaya

ID │FLAGS │SUBJECT │FROM │DATE 
```

This when `maildir.root-dir = "/home/renesat/.mail/mainmail/inbox`:
```
> himalaya

ID │FLAGS │SUBJECT                                     │FROM                 │DATE                   
18 │      │***                                         │***                  │2023-09-02 19:27+00:00 
19 │      │***                                         │***                  │2023-08-01 12:58+00:00 
```

Can I use Maildir folder with subfolders for my account?

**Comment by soywod** [comment]
Which version of Himalaya do you use?

**Comment by renesat** [comment]
> Which version of Himalaya do you use?

I use version from nixos-unstable: `himalaya 1.0.0-beta.4`

**Comment by soywod** [comment]
I would advise to either use `master` branch or wait for the `v1`. New versions support collections of Maildir (alla mbsync), while previous version were only supporting Maildir++ variant.

**Comment by renesat** [comment]
Ok. Try to check `master` version, but I have error when build using flake:
```
error: Cannot find Git revision 'b40ca9d9e161b91e9efcb762fa05f06e3fe46f63' in ref 'refs/heads/master' of repository 'https://github.com/pimalaya/tui'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
```

But it's work when I build using `cargo` and `nix develop`...

**Comment by renesat** [comment]
Also when using `master` version maildir expect `INBOX` folder, but mbsync create `inbox`:

```
Error: 
   0: cannot find maildir matching name INBOX

Note: Run with --debug to enable logs with spantrace.
Note: Run with --trace to enable verbose logs with backtrace.
```

And all work if rename inbox folder.

**Comment by soywod** [comment]
> Try to check `master` version, but I have error when build using flake:

I'm in the process of cleaning core libs and releasing `v1`, it should be fixed as soon as I merge all of them on Himalaya CLI.

> Also when using `master` version maildir expect `INBOX` folder, but mbsync create `inbox`:

Yes, `mbsync` creates a `Inbox` folder, but the default name for IMAP (and for Himalaya as well) is `INBOX`.

> EDIT: I can solve this with `folder.alias.inbox = "inbox"`, but it's not as friendly.

What do you mean by not as friendly? Defining an alias is the way to go, Himalaya CLI cannot know in advance the name of your mailboxes/folders.

**Comment by renesat** [comment]
> What do you mean by not as friendly? Defining an alias is the way to go, Himalaya CLI cannot know in advance the name of your mailboxes/folders.

Yes, I just suggested associating `INBOX` with `inbox`, by default, but I think the IMAP argument is enough to not bother with it :)
