### ISSUE TITLE
Error Installing on NixOS Linux x86-64

### ISSUE THREAD

**Issue by Locorock** [pimalaya/himalaya#491]
Trying to install himalaya from flake but i'm getting an error referring to Git revisions in pimalaya/tui: 
```nix
error: Cannot find Git revision 'b40ca9d9e161b91e9efcb762fa05f06e3fe46f63' in ref 'refs/heads/master' of repository 'https://github.com/pimalaya/tui'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
```
I tried simply installing it from nixpkgs but it fails to install pimalaya to .local so it crashes as soon as i start it.

**Comment by Locorock** [comment]
oh, it seems like installing from cargo also fails, due to pimalaya_tui::prompt not existing for some reason

**Comment by soywod** [comment]
I'm still stabilizing core libs before releasing Himalaya CLI v1, I would advise to wait few days. I let you know.

**Comment by soywod** [comment]
Should definitely work better now. You can either build yourself the `master` branch, or take a pre-release at https://github.com/pimalaya/himalaya/actions/runs/11580388478.
