### ISSUE TITLE
Pre-release packaging: Windows .zips bundle duplicate binaries

### ISSUE THREAD

**Issue by torculus** [pimalaya/himalaya#492]
1. Choose any recent pre-release build (e.g. [this one](https://github.com/pimalaya/himalaya/actions/runs/11580388478)) and download the Windows `.zip` file
2. Extract it, then enter the directory and extract that too
3. You'll find `himalaya.exe` as well as another `himalaya.zip`
    * ![image](https://github.com/user-attachments/assets/3fc4316b-0c5c-4fa8-b602-2e4e8ef48041)
4. When you open up the second `.zip` file, you'll find a duplicate copy of `himalaya.exe` (the file names, sizes, and hashes match identically)
    * ![image](https://github.com/user-attachments/assets/c4782804-212b-4c78-8273-82ba7313372e)
5. So the application is being bundled *twice*

**Comment by soywod** [comment]
There is in fact 2 problems:

1. The tar archive ends up being archived with the zip one (not the opposite)
2. The release is bundled twice. It looks like the GitHub action that uploads artifacts [does a zip on its own](https://github.com/actions/upload-artifact?tab=readme-ov-file#zip-archives), and it's not customizable:
  > When an Artifact is uploaded, all the files are assembled into an immutable Zip archive. There is currently no way to download artifacts in a format other than a Zip or to download individual artifact contents.

Thank you for pointing it out!

**Comment by soywod** [comment]
Fixed on `master`, see <https://github.com/pimalaya/himalaya/actions/runs/11596856458>.
