### ISSUE TITLE
Better version management

### ISSUE THREAD

**Issue by lyz-code** [pimalaya/himalaya#513]
It would be nice if you could do releases with the different fixes so that if an upgrade goes wrong we can go back to a working one. 

As the last one has failed to upgrade I can't use `himalaya` anymore until you fix it.

I'm trying to use `--rev {commit_id}` going back in the history to try to make one work, but it's a cumbersome process.

Thanks!

**Comment by lyz-code** [comment]
The last release `v1.0.0-beta4` does not work with the latest config syntax:

```
Error: 
   0: cannot parse config file at "~/.config/himalaya/config.toml"
   1: TOML parse error at line 538, column 14
   1:     |
   1: 538 | message.send.backend.type = "smtp"
   1:     |              ^^^^^^^
   1: wanted exactly 1 element, more than 1 element
   1: 
```

Please help me (╥﹏╥)

**Comment by soywod** [comment]
I'm sorry for that, I admit that version management was not optimal starting from `v1.0.0-beta`s. The beta statement prevented the tool to be packaged and updated to main repositories (which I was not aware of before), and I delayed too much since the last release.

I have literally 1 major task and 1 minor one before releasing the final `v1`. Starting for there, all should unlock smoothly. I will just ask for a bit more patience :pray: 

Try with the `v1.0.0` branch of Himalaya CLI, you may have more chance to make it work. But I would advise to wait for the last major task to land.

**Comment by lyz-code** [comment]
Hi @soywod thanks for the quick answer as always. Sadly `cargo install --git https://github.com/pimalaya/himalaya.git --force --branch v1.0.0 himalaya ` gave the same `start-tls` error as `master` :(. 

It is probably my fault to have assumed the software was stable enough to use it (even though you added the disclaimer). The thing is that I've already migrated all my email management to `himalaya` and I feel kind of lost. Is there anything that I can do to at least make it work until the first stable version is out?

**Comment by soywod** [comment]
Somehow I was able to install himalaya from `master`, so you may have updated your dependencies instead of locking them to the `Cargo.lock`. Could you try the following?

```bash
cargo clean
cargo install --frozen --force --git https://github.com/pimalaya/himalaya.git
```

**Comment by soywod** [comment]
If you do not use specific cargo features (only the default ones), you can also download a binary from the [pre-releases](https://github.com/pimalaya/himalaya/actions) GitHub workflow.

**Comment by lyz-code** [comment]
I've tried running the commands you told me on the latest version of master:

```bash
$: git pull
Already up to date.
$: cargo clean 
     Removed 0 files
$: cargo install --frozen --force --git https://github.com/pimalaya/himalaya.git 
    Updating git repository `https://github.com/pimalaya/himalaya.git`
error: failed to fetch into: ~/.cargo/git/db/himalaya-1e70121402046f0a

Caused by:
  attempting to update a git repository, but --frozen was specified
$: rm -r ~/.cargo/git/db/himalaya-1e70121402046f0a -f
$: cargo install --frozen --force --git https://github.com/pimalaya/himalaya.git
    Updating git repository `https://github.com/pimalaya/himalaya.git`
error: failed to clone into: /home/lyz/.cargo/git/db/himalaya-1e70121402046f0a

Caused by:
  attempting to update a git repository, but --frozen was specified
$: cargo install --force --git https://github.com/pimalaya/himalaya.git
    Updating git repository `https://github.com/pimalaya/himalaya.git`
  Installing himalaya v1.0.0 (https://github.com/pimalaya/himalaya.git#6e658fef)
    Updating git repository `https://github.com/pimalaya/core`
    Updating git repository `https://github.com/pimalaya/tui`
    Updating crates.io index
    Updating git repository `https://github.com/pimalaya/imap-client`
    Updating git repository `https://github.com/soywod/imap-next`
error: failed to compile `himalaya v1.0.0 (https://github.com/pimalaya/himalaya.git#6e658fef)`, intermediate artifacts can be found at `/tmp/cargo-installJxqxkb`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  no matching package named `start-tls` found
  location searched: https://github.com/pimalaya/core
  required by package `imap-client v0.1.5 (https://github.com/pimalaya/imap-client#bca40484)`
      ... which satisfies git dependency `imap-client` of package `email-lib v0.26.0 (https://github.com/pimalaya/core#7ac99d0b)`
      ... which satisfies dependency `email-lib = "=0.26"` of package `himalaya v1.0.0 (/home/lyz/.cargo/git/checkouts/himalaya-1e70121402046f0a/6e658fe)`
```

Downloading the binary from the pre-releases worked just fine. Thank you sooo much! <3
