### ISSUE TITLE
missing field `method` when configuring Outlook profile with OAuth2

### ISSUE THREAD

**Issue by dimanngo** [pimalaya/himalaya#532]
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/9eb86895-ade0-438c-92d8-77040ba17095" />

<img width="2200" alt="image" src="https://github.com/user-attachments/assets/64007787-6941-4ee2-b3e8-33eacecd842b" />

**Comment by soywod** [comment]
The error message is not fully accurate, it's a bug from the `toml` crate (more specifically the `serde` crate, see <https://github.com/toml-rs/toml/issues/802>. You miss the [`backend.auth.method`](https://github.com/pimalaya/himalaya/blob/5eeda248fd90d161c8b346604f603d4a0a37ec6d/config.sample.toml#L421).
